

version: "3.5"

volumes:
   wordpress:
     name: wordpress
     driver: local
     driver_opts:
        device: /home/ffons-ti/INCEPTION/srcs/web
        o: bind
        type: none
   mariadb:
     name: mariadb
     driver: local
     driver_opts:
        device: /home/ffons-ti/INCEPTION/srcs/database  
        o: bind
        type: none

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/.
    depends_on:
     - wordpress
     - mariadb
    ports:
     - "443:443"
    volumes:
     - wordpress:/var/www/html
    networks:
     inception:
    env_file:
     - .env
    restart: always
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    depends_on:
     - mariadb
    volumes:
     - wordpress:/var/www/html
    networks:
     inception:
    env_file:
     - .env
    expose:
     - "9000"
    restart: always
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
     - mariadb:/var/lib/mysql
    networks:
     inception:
    env_file:
     - .env
    expose:
     - "3306"
    restart: always
networks:
  inception:
    name: inception
    driver: bridge
