

version: "3.5"

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/.
    depends_on:
     - wordpress
     - mariadb
    ports:
     - "443:443"
    volumes:
     - ./web:/var/www/html
    networks:
     inception:
    env_file:
     - .env
    restart: always
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    depends_on:
     - mariadb
    volumes:
     - ./web:/var/www/html
    networks:
     inception:
    env_file:
     - .env
    restart: always
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
     - ./database:/var/lib/mydwl
    networks:
     inception:
    env_file:
     - .env
    restart: always
networks:
  inception:
    name: inception
